//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// BSch.rc で使用
//
#define _USING_V110_SDK71_              1
#define IDOK2                           2
#define IDC_REPLACE_COMPINDEX           3
#define IDC_EDIT_COMPINDEX              4
#define IDD_ABOUTBOX                    100
#define ID_BSCH_STATUS_BAR              101
#define IDD_SELECT_PARTS                102
#define IDD_SETLIB_DLG                  103
#define ID_TIMER_RBUTTONDOWN            105
#define IDM_EXTMENU_0                   106
#define IDM_EXTMENU_1                   107
#define IDM_EXTMENU_2                   108
#define IDM_EXTMENU_3                   109
#define IDM_EXTMENU_4                   110
#define IDM_EXTMENU_5                   111
#define IDM_EXTMENU_6                   112
#define IDM_EXTMENU_7                   113
#define IDM_EXTMENU_8                   114
#define IDM_EXTMENU_9                   115
#define ID_QUICKPROPCOMPONENT           116
#define IDR_MAINFRAME                   128
#define IDR_BSCHTYPE                    129
#define IDS_FNAME_EXPO_EMF              129
#define IDS_EXPO_EMF_ERROR              130
#define IDS_COL_JUNC                    131
#define IDS_COL_WIRE                    132
#define IDS_COL_BUS                     133
#define IDC_CUR_NORMAL                  134
#define IDS_COL_DASH                    134
#define IDC_CUR_MOVE                    135
#define IDS_COL_TAG                     135
#define IDD_ATRIB_PART                  136
#define IDS_COL_TAG_NAME                136
#define IDS_COL_COMMENT                 137
#define IDD_ATRIB_TAG                   138
#define IDS_COL_LABEL                   138
#define IDI_TAG_SQ                      139
#define IDS_COL_XOR                     139
#define IDI_TAG_L                       140
#define IDS_COL_PART                    140
#define IDI_TAG_LR                      141
#define IDS_COL_PART_PINNAME            141
#define IDI_TAG_R                       142
#define IDS_COL_PART_PINNUM             142
#define IDD_ATRIB_COMMENT               143
#define IDS_COL_PART_NAME               143
#define IDD_ATRIB_LABEL                 144
#define IDS_COL_PART_NUM                144
#define IDR_FLOATINGMENU                145
#define IDS_COL_PART_FRAME              145
#define IDS_COL_SHEET_FRAME             146
#define IDS_COL_SHEET_GRID              147
#define IDD_SET_PRINT_OPTION            148
#define IDS_COL_DARK                    148
#define IDS_DEFAULT_COLOR               149
#define IDS_COL_PART_PIN                150
#define IDC_CUR_PLACE                   151
#define IDS_FINISH_FIND                 151
#define IDS_COL_BG                      152
#define IDS_BG_NOT_PRINT                153
#define IDS_INVALID_MARGIN              154
#define IDD_SETLAYER                    155
#define IDS_EXTMENU_TITLE               155
#define IDS_COL_ZLPIN                   156
#define IDS_COL_NC_MARK                 157
#define IDC_CUR_CC_MOVE                 158
#define IDS_LAYER_DBAR_TITLE            158
#define IDD_SETSHEETSIZE                159
#define IDS_INVALID_LINEWIDTH           159
#define IDD_SETFONT                     160
#define IDS_UNREG_FILETYPE              160
#define IDD_SETCOLOR                    161
#define IDS_REG_FILETYPE                161
#define IDD_FIND                        162
#define IDS_URL                         162
#define IDD_DBAR_LAYER                  163
#define IDS_DISCARD_CHANGES_COMMENT     163
#define IDC_CUR_SCRL                    164
#define IDS_COL_QUICKPROPVIEW           164
#define IDS_COL_TEMPFRAME_FOCUSED       165
#define IDD_ATRIB_MARKER_LINE           166
#define IDS_COL_TEMPFRAME_NOT_FOCUSED   166
#define IDD_SETQUICKPROP                167
#define IDS_IMAGE_IMPORT                167
#define IDS_INVALID_IMAGE_MAGNIFICATION 168
#define IDB_EDIT                        169
#define IDS_INVALID_MARKSIZE            169
#define IDB_BITMAP2                     170
#define IDB_VIEW                        170
#define IDS_LATERVERSION                170
#define IDD_TAG_FRAME                   171
#define IDS_VERSION                     171
#define IDB_IMAGE_PTN                   172
#define IDS_DISCARD_AND_RELOAD          172
#define IDB_IMAGE_SEL_PTN               173
#define IDS_MSGLINE_SPACE_CHANGE_DIR    173
#define IDD_IMAGE_ATRB                  174
#define IDS_MSGLINE_WIRE_ESC            174
#define IDD_SET_HIDING_NUM_VAL          175
#define IDS_FIND2_COLUMN_TEXT           175
#define IDD_OBJECTFILTER                176
#define IDS_FIND2_COLUMN_TYPE           176
#define IDS_FINDTYPE_REFNUM             177
#define IDS_FINDTYPE_VALUE              178
#define IDB_TOOLBUTTONS                 179
#define IDS_FINDTYPE_NAMEINLIB          179
#define IDS_FINDTYPE_MFR                180
#define IDS_FINDTYPE_MFRPN              181
#define IDS_FINDTYPE_PACKAGE            182
#define IDS_FINDTYPE_NOTE               183
#define IDB_OBJFILTER                   184
#define IDS_FINDTYPE_TAG                184
#define IDD_SETCOLOR2                   185
#define IDS_FINDTYPE_Label              185
#define IDC_CURSOR_NULL                 186
#define IDS_FINDTYPE_COMMENT            186
#define IDB_BITMAP_LINEENDSTYLE         187
#define IDS_FIND_MARK                   187
#define IDS_COL_FIND_MARK               187
#define IDS_SHARED_BLOCK                188
#define IDS_FIXED_BLOCK                 189
#define IDB_BITMAP_DECOLINESTYLE        190
#define IDS_BLOCK                       190
#define IDD_DIALOG_SETDECOLINE          191
#define IDS_INVALID_EXP_IMAGE_MAG       191
#define IDD_FIND2                       192
#define IDD_FIND2_OPTION                193
#define IDB_BITMAP_SORTMARK             194
#define IDD_DIALOG_DISPBLOCK            195
#define IDC_EDIT_PARTNUM                1001
#define IDC_SPIN_PARTBLOCK              1002
#define IDC_EDIT_PARTBLOCK              1003
#define IDC_LIST_LIBRARY                1004
#define IDC_ORGNAME                     1004
#define IDC_LIB_LIST                    1006
#define IDC_EDIT_PARTNAME               1006
#define IDC_EDIT_TAGNAME                1006
#define IDC_LIB_UP                      1007
#define IDC_LIST_PARTNAME               1007
#define IDC_EDIT_MFR                    1007
#define IDC_LIB_DOWN                    1008
#define IDC_TAG_SQ                      1008
#define IDC_EDIT_MFR_PNUM               1008
#define IDC_EDIT_MFR2                   1008
#define IDC_LIB_ADD                     1009
#define IDC_TAG_L                       1009
#define IDC_EDIT_PKG                    1009
#define IDC_EDIT_MFR_PNUM2              1009
#define IDC_LIB_DEL                     1010
#define IDC_TAG_R                       1010
#define IDC_EDIT_PKG2                   1010
#define IDC_TAG_LR                      1011
#define IDC_LIB_ABS                     1011
#define IDC_EDIT_COMMENT                1012
#define IDC_CHECK_SMALLFONT             1013
#define IDC_LIB_REL                     1013
#define IDC_EDIT_LABELNAME              1014
#define IDC_PIN_NUM                     1015
#define IDC_PREVIEW                     1016
#define IDC_CHECK_FRAME                 1022
#define IDC_CHECK_PARTNUM               1024
#define IDC_CHECK_EDIT_HIGHLIGHT        1024
#define IDC_CHECK_RES_AUTO              1025
#define IDC_CHECK_PAGEFIT               1025
#define IDC_EDIT_RES                    1026
#define IDC_CHECK_PARTNAME              1027
#define IDC_BUTTON_FONT                 1027
#define IDC_CHECK_PRINTBMP              1028
#define IDC_EDIT_NOTE                   1029
#define IDC_CHECK_PRINTBMP2             1029
#define IDC_CHECK_PRINT_COLOR           1029
#define IDC_COM_FONTNAME                1030
#define IDC_EDIT_UPPER_M                1030
#define IDC_LBL_FONTNAME                1031
#define IDC_EDIT_LEFT_M                 1031
#define IDC_COM_FONTSTYLE               1032
#define IDC_EDIT_LOWER_M                1032
#define IDC_LBL_FONTSTYLE               1033
#define IDC_EDIT_RIGHT_M                1033
#define IDC_EDIT_X                      1034
#define IDC_COM_FONTSIZE                1034
#define IDC_EDIT_Y                      1035
#define IDC_LBL_FONTSIZE                1035
#define IDC_EDIT_IMAGE_MAG              1035
#define IDC_SET_COMFONT                 1036
#define IDC_SET_LBLFONT                 1037
#define IDC_LIST                        1037
#define IDC_CHANGE_COL                  1038
#define IDC_NAME_FONTNAME               1038
#define IDC_BUTTON_SUIGYODO             1038
#define IDC_STATIC_COL                  1039
#define IDC_NAME_FONTSTYLE              1039
#define IDC_DEFAULT_COLOR               1040
#define IDC_FINDSTRING                  1040
#define IDC_NAME_FONTSIZE               1040
#define IDC_FIND_NUM                    1041
#define IDC_SET_NAMEFONT                1041
#define IDC_FIND_NAME                   1042
#define IDC_CHECK_NUMVERT               1042
#define IDC_QUICKPROP_FONTNAME          1043
#define IDC_FIND_NAME_LIB               1043
#define IDC_CHECK_NAMEVERT              1043
#define IDC_QUICKPROP_FONTSTYLE         1044
#define IDC_FIND_TAG                    1044
#define IDC_EDIT_LIB_NOTE               1044
#define IDC_QUICKPROP_FONTSIZE          1045
#define IDC_FIND_LABEL                  1045
#define IDC_SET_QUICKPROPFONT           1046
#define IDC_FIND_COMMENT                1046
#define IDC_CHECK_ENABLE_WIDTH          1046
#define IDC_FIND_MATCHWHOLE             1047
#define IDC_EDIT_WIDTH                  1047
#define IDC_MYSTDSHEETSIZE              1048
#define IDC_CHECK_ENABLE_TAG            1048
#define IDC_FIND_MATCHWHOLE2            1048
#define IDC_FIND_CASE_SENSITIVE         1048
#define IDC_ADD                         1049
#define IDC_DEL                         1050
#define IDC_D0                          1050
#define IDC_D1                          1051
#define IDC_EDIT_LINEWIDTH              1051
#define IDC_D2                          1052
#define IDC_SPIN_LINEWIDTH              1052
#define IDC_D3                          1053
#define IDC_BUTTON_SETCOLOR             1053
#define IDC_D4                          1054
#define IDC_STATIC_COLOR                1054
#define IDC_D5                          1055
#define IDC_STATIC_RANGE_WIDTH          1055
#define IDC_D6                          1056
#define IDC_D7                          1057
#define IDC_CHECK_PRINTBG_WHITE         1057
#define IDC_STATIC_WIDTH_TITLE          1058
#define IDC_CHECK_MFR                   1059
#define IDC_CHECK_MFRPN                 1060
#define IDC_CHECK_PKG                   1061
#define IDC_CHECK_NOTE                  1062
#define IDC_CHECK_NAMEINLIB             1063
#define IDC_CHECK_USE_QUICKPROP         1064
#define IDC_CHECK_NUM                   1065
#define IDC_STATIC_VIEW                 1065
#define IDC_CHECK_NUM2                  1066
#define IDC_EDIT_MAG                    1066
#define IDC_CHECK_VAL                   1066
#define IDC_STATIC_EDIT                 1066
#define IDC_CHECK_USE_MOUSEHOVER        1067
#define IDC_CHECK_ON_MOUSEHOVER         1067
#define IDC_CHECK_HIDENUM               1068
#define IDC_CHECK_HIDEVAL               1069
#define IDC_E0                          1070
#define IDC_E1                          1071
#define IDC_F_PART                      1071
#define IDC_E2                          1072
#define IDC_F_BUS                       1072
#define IDC_E3                          1073
#define IDC_F_WIRE                      1073
#define IDC_E4                          1074
#define IDC_F_DASH                      1074
#define IDC_E5                          1075
#define IDC_F_JUNCTION                  1075
#define IDC_E6                          1076
#define IDC_F_MARKER                    1076
#define IDC_E7                          1077
#define IDC_F_BENTRY                    1077
#define IDC_F_WENTRY                    1078
#define IDC_F_TAG                       1079
#define IDC_F_LABEL                     1080
#define IDC_F_COMMENT                   1081
#define IDC_F_COMMENT2                  1082
#define IDC_F_IMAGE                     1082
#define IDC_FIND_MANUFACTURE            1087
#define IDC_FIND_PACKAGE                1088
#define IDC_FIND_MANUFACTUREPN          1089
#define IDC_COMBOBOXEX_LINESTYLE        1089
#define IDC_FIND_NOTE                   1090
#define IDC_EDIT_ENDMARKSIZE            1092
#define IDC_CHECK_CURVE                 1093
#define IDC_COMBOBOXEX_STARTPOINT       1094
#define IDC_COMBOBOXEX_ENDPOINT         1095
#define IDC_SPIN_ENDMARKSIZE            1100
#define IDC_STATIC_VERSION              1101
#define IDC_EDIT_TEXT                   1102
#define IDC_BUTTON_SEARCH               1103
#define IDC_LIST_FOUND                  1104
#define IDC_BUTTON_OPTION               1105
#define IDC_CHECK_FOOTER                1106
#define IDC_EDIT1                       1107
#define IDC_EDIT_FOOTER                 1107
#define IDC_RADIO_NOTDISPLAY            1108
#define IDC_RADIO_NUM                   1109
#define IDC_STATIC_BLOCK_STATUS         1109
#define IDC_RADIO_ALP                   1110
#define ID_TOOL_WIRE                    32772
#define ID_TOOL_BUS                     32773
#define ID_TOOL_DASH                    32774
#define ID_TOOL_JUNCTION                32775
#define ID_TOOL_ENTRY_BL                32777
#define ID_TOOL_ENTRY_BR                32778
#define ID_TOOL_ENTRY_WL                32779
#define ID_TOOL_ENTRY_WR                32780
#define ID_TOOL_LABEL                   32781
#define ID_TOOL_ENTRY                   32782
#define ID_TOOL_TAG                     32784
#define ID_TOOL_COMMENT                 32785
#define ID_TOOL_PART                    32786
#define ID_TOOL_SELECTOR                32787
#define ID_TOOL_DRAG                    32789
#define ID_ZOOM_IN                      32791
#define ID_ZOOM_OUT                     32792
#define ID_EDIT_ATTRIBUTE               32793
#define ID_SET_LIBRARY                  32794
#define ID_SET_COMMENT_FONT             32795
#define ID_SET_SHEETSIZE                32796
#define ID_PART_FRAME                   32797
#define ID_DISP_GRID                    32798
#define ID_SNAP_GRID                    32799
#define ID_SHEET_640                    32800
#define ID_SHEET_1000                   32801
#define ID_SHEET_1600                   32802
#define ID_SHEET_2000                   32803
#define ID_SHEET_3000                   32804
#define ID_MIRROR                       32805
#define ID_ROTATE                       32806
#define ID_EDIT_DELETE                  32807
#define ID_REFRESH                      32808
#define ID_FILE_EXPO_BMP                32809
#define ID_FILE_EXPO_BID                32811
#define ID_FILE_PRINT_OPTION            32812
#define ID_USE_PREVIEW                  32813
#define ID_EDIT_MOVETOLAYER0            32814
#define ID_EDIT_MOVETOLAYER1            32815
#define ID_EDIT_MOVETOLAYER2            32816
#define ID_EDIT_MOVETOLAYER3            32817
#define ID_EDIT_MOVETOLAYER4            32818
#define ID_EDIT_MOVETOLAYER5            32819
#define ID_EDIT_MOVETOLAYER6            32820
#define ID_EDIT_MOVETOLAYER7            32821
#define ID_EDIT_SETUPLAYER              32822
#define ID_FILE_NEW_SHEET               32823
#define ID_SHEET_FREE                   32824
#define ID_MENU_CROSS_CURSOR            32826
#define ID_FILE_EXPO_EMF                32828
#define ID_SET_COLOR                    32834
#define ID_Menu                         32836
#define ID_EDIT_FINDNEXT                32838
#define ID_EDIT_EMF_COPY                32844
#define ID_SET_COARSE_STEP_ZOOM         32846
#define ID_DISP_NCMARK                  32848
#define ID_VIEW_LAYERBOX                32850
#define ID_32851                        32851
#define ID_TOOL_MARKER                  32854
#define ID_DISP_HIDDENPINNUM            32857
#define ID_SETUP_ALLOWAPPENDSELECT      32858
#define ID_SETUP_QUICK                  32859
#define ID_EDIT_BULKATTRIBUTE           32862
#define ID_CONVERT_T2L                  32869
#define ID_CONVERT_T2C                  32870
#define ID_CONVERT_L2T                  32871
#define ID_CONVERT_L2C                  32872
#define ID_CONVERT_C2T                  32873
#define ID_CONVERT_C2L                  32874
#define ID_BULKATTRIBUTE_TAGFRAME       32875
#define ID_BULKATTRIBUTE_MARKERLINE     32876
#define ID_BULKATTRIBUTE_COMMENTFONT    32877
#define ID_BULKATTRIBUTE_REPLACECOMPONENTINFO 32878
#define ID_INSERT_BITMAP                32879
#define ID_BULKATTRIBUTE_HIDENUMBERS    32880
#define ID_TOOL_USEOBJECTFILTER         32882
#define ID_FLOAT_MOVEENDPOINT           32883
#define ID_EDIT_MOVEENDPOINT            32884
#define ID_EDIT_POINTS                  32885
#define ID_EDIT_EDIT                    32886
#define ID_SETUP_PLACELINEBYCLICK       32887
#define ID_EDIT_ORDER                   32888
#define ID_ORDER_BRINGTOFRONT           32889
#define ID_ORDER_BRINGTOBACK            32890
#define ID_FLOAT_ORDER                  32891
#define ID_FILE_RELOAD                  32892
#define ID_RELOAD_RELOAD                32893
#define ID_BULKATTRIBUTE_DECORATIONLINE 32894
#define ID_FILE_RECENTFILE              32895
#define ID_FLOAT_EDIT_WITH_LCOV         32896
#define ID_SETUP_BLOCK                  32897
#define ID_SETUP_DISPBLOCK              32898
#define IDS_LIBSET_VALID_NEXT           61447
#define IDS_FILEREADERROR               61448
#define IDS_SETFONT_VALIDNEXT           61449
#define IDS_NOT_FOUND_PART              61450
#define IDS_FNAME_EXPO_BMP              61451
#define IDS_EXPO_BMP_ERROR              61452
#define IDS_EXPO_BID_ERROR              61453
#define IDS_LIB_ADD_NEW                 61454
#define IDS_FNAME_EXPO_BID              61455
#define IDS_INVALID_RESOLUTION          61456
#define IDS_INVALID_SHEETSIZE           61459

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        196
#define _APS_NEXT_COMMAND_VALUE         32899
#define _APS_NEXT_CONTROL_VALUE         1110
#define _APS_NEXT_SYMED_VALUE           119
#endif
#endif
