//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// LCoV.rc で使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_PINPROPGRID                  102
#define IDD_DIALOGBAR                   103
#define IDC_CBOX_PINTYPE                103
#define IDC_EDIT_GRIDTEXT               104
#define ID_PINPROPGRIDTITLE             105
#define IDR_MAINFRAME                   128
#define IDR_LCoVTYPE                    129
#define IDS_PARTSIZE_RANGE              129
#define IDS_PART_BLOCKRANGE             130
#define IDS_PARTNAME_INVALID            131
#define IDS_STRING_CREATE_BPTN          132
#define IDI_ICON_DOWN                   133
#define IDS_STRING_SAVE_CURRENT         133
#define IDI_ICON_UP                     134
#define IDS_TOOL_SELECT                 134
#define IDS_NOTICE_SORT                 135
#define IDC_CURSOR_MOVE                 136
#define IDS_SAVE_ERROR                  136
#define IDD_DIALOG_PIN_PROP             137
#define IDS_GRID_TITLE_POS              137
#define IDS_GRID_TITLE_NAME             138
#define IDB_BMP_PIN_SMALL               139
#define IDS_GRID_TITLE_TYPE             139
#define IDB_BMP_PIN_NEGA                140
#define IDS_GRID_TITLE_HIDE             140
#define IDB_BMP_PIN_NEGACK              141
#define IDS_GRID_TITLE_NUM              141
#define IDB_BMP_PIN_NORM                142
#define IDS_GRID_TITLE_BLOCK            142
#define IDB_BMP_PIN_CK                  143
#define IDS_VERSION                     143
#define IDD_DLG_PROP_COMP               144
#define IDS_STRING144                   144
#define IDS_LATERVERSION                144
#define IDD_PTN_PROP                    145
#define IDS_PART_FIXEDBLOCKRANGE        145
#define IDD_DIALOG_PROP_LIB             146
#define IDD_DIALOG_ALIAS                147
#define IDD_PTNTEXT                     148
#define IDB_BMP_PIN_ZLENG               149
#define IDR_COMPEDITCONTEXT             150
#define IDR_COMPNAMECONTEXT             151
#define IDD_PINPROPS                    152
#define IDB_BMP_CHK                     153
#define IDB_BITMAP_PINTYPELIST          154
#define IDI_ICON_DIVIDEMARK             156
#define IDD_DISPNAMESETTING             157
#define IDD_LINE_PROP                   158
#define IDC_BUTTON_UP                   1000
#define IDC_BUTTON_DOWN                 1001
#define IDC_EDIT_PIN_NAME               1003
#define IDC_EDIT_PIN_NUM                1004
#define IDC_EDIT_BLOCK                  1005
#define IDC_SPIN_BLOCK                  1006
#define IDC_CHECK_HIDE_NUM              1007
#define IDC_RADIO_NORM                  1014
#define IDC_RADIO_CK                    1015
#define IDC_EDIT_COMP_NAME              1015
#define IDC_RADIO_NEGA                  1016
#define IDC_EDIT_COMP_REF               1016
#define IDC_RADIO_NEGACK                1017
#define IDC_EDIT_COMP_SIZEX             1017
#define IDC_RADIO_SMALL                 1018
#define IDC_EDIT_COMP_BLOCK             1018
#define IDC_EDIT_COMP_SIZEY             1019
#define IDC_RADIO_ZLENG                 1019
#define IDC_CHECK_USEPTN                1020
#define IDC_CHECK_NOBIT                 1021
#define IDC_CHECK_USEPTN2               1021
#define IDC_CHECK_DASHSTYLE             1022
#define IDC_EDIT_MFR                    1022
#define IDC_CHECK_FILL                  1023
#define IDC_EDIT_MFRPN                  1023
#define IDC_CHECK_CURVELINE             1023
#define IDC_COMBO_WIDTH                 1024
#define IDC_EDIT_PKG                    1024
#define IDC_EDIT_NOTE                   1025
#define IDC_EDIT_COMP_FIXBLOCK          1026
#define IDC_EDIT_COMP_FIXEDBLOCK        1026
#define IDC_EDIT_STRING                 1027
#define IDC_EDIT_NAME                   1028
#define IDC_EDIT_ALIAS                  1029
#define IDC_EDIT_TEXT                   1030
#define IDC_RADIO_HL                    1031
#define IDC_RADIO_HC                    1032
#define IDC_RADIO_HR                    1033
#define IDC_RADIO_VT                    1034
#define IDC_RADIO_VC                    1035
#define IDC_RADIO_VB                    1036
#define IDC_CHECK_COMFONG               1037
#define IDC_CHECK_COMFONT               1037
#define IDC_BUTTON_FONT                 1038
#define IDC_VSCROLL                     1039
#define IDC_HSCROLL                     1040
#define IDC_STATIC_                     1043
#define IDC_STATIC_VERSION              1043
#define IDC_LIST_NAMES                  1047
#define IDC_BUTTONSHOW_ALL              1048
#define IDC_BUTTONHIDE_ALL              1049
#define IDC_BUTTON_SHOWHIDE_NAME        1049
#define IDC_CHECK_FIXEDBLOCKNUM         1050
#define IDC_CHECK_SHARED_BLOCK          1051
#define ID_Menu                         32773
#define IDC_LIST_NAME                   32774
#define ID_FLOAT_BUHINN                 32775
#define ID_EDIT_CUT_COMP                32777
#define ID_EDIT_COPY_COMP               32780
#define ID_EDIT_PASTE_COMP              32781
#define ID_VIEW_ZOOMOUT                 32784
#define ID_VIEW_ZOOMIN                  32785
#define ID_TOOL_SELECT                  32786
#define ID_TOOL_PIN                     32788
#define ID_TOOL_LINE                    32789
#define ID_TOOL_CIRCLE                  32790
#define ID_TOOL_POLYGON                 32791
#define ID_TOOL_ARC                     32793
#define ID_EDIT_PROPERTY                32803
#define ID_Menu32804                    32804
#define ID_EDIT_NEW_COMP                32808
#define ID_EDIT_PROPERTY_COMP           32810
#define ID_EDIT_MIRROR                  32812
#define ID_EDIT_ROTATE                  32814
#define ID_EDIT_NODE_MODE               32818
#define ID_TOOL_CREATE_BPTN             32820
#define ID_EDIT_PROP_LIB                32827
#define ID_EDIT_ADD_ALIAS               32829
#define ID_Menu32830                    32830
#define ID_EDIT_SORT_COMPONENT          32832
#define ID_TOOL_TEXT                    32833
#define ID_EDIT_NEXTPINNUM              32837
#define ID_EDIT_NEXTPINNAME             32838
#define ID_Menu32847                    32847
#define ID_FLOAT_32856                  32856
#define ID_VIEW_PINPROPS_WND            32864
#define ID_FLOAT_PROPERTY               32865
#define ID_FLOAT_ADDNODE                32866
#define ID_ADD_NODE                     32867
#define ID_VIEW_SWAPNAMEANDNUM          32870

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32871
#define _APS_NEXT_CONTROL_VALUE         1052
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
